export declare function getRepoConfigPath(repoPath: string): string;
export declare function existsRepoConfig(repoPath: string): Promise<boolean>;
export declare function existsRepoConfigSync(repoPath: string): boolean;
export declare function _readRepoConfigFile<T>(file: string): Promise<T>;
export declare function _readRepoConfigFileSync<T>(file: string): T;
export declare function _writeRepoConfigFile<T>(file: string, config: T): Promise<void>;
export declare function _writeRepoConfigFileSync<T>(file: string, config: T): void;
export declare function readRepoConfig<T>(repoPath: string): Promise<T>;
export declare function readRepoConfigSync<T>(repoPath: string): T;
export declare function writeRepoConfig<T>(repoPath: string, config: T): Promise<void>;
export declare function writeRepoConfigSync<T>(repoPath: string, config: T): void;
